name: build
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: ['3.7', '3.10']
        include:
          - os: windows-latest
            py: "3.10"
          - os: macos-latest
            py: "3.10"
    name: "Run Tests on ${{ matrix.os }}, py${{ matrix.py }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: install requirements
        run: python -m pip install tox
      - name: lint
        run: python -m tox -e lint,mypy
      - name: test
        run: python -m tox -e py
      - name: twine-check
        run: python -m tox -e twine-check
